version: '3'
services:
  mongodb:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: Pass#word
  api:
    container_name: api-container
    build: .
    ports:
      - '4000:80'
    links:
      - mongodb
    environment:
      MongoDbSettings:Host: mongodb
      MongoDbSettings:Password: Pass#word
